default_language_version:
  python: python3.8.2
repos:
  -   repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.0.1
      hooks:
        - id: trailing-whitespace
        - id: end-of-file-fixer
        - id: check-added-large-files
        - id: check-docstring-first
        - id: check-yaml
          exclude: ^devops/
        - id: check-json
        - id: debug-statements
  -   repo: https://github.com/pycqa/isort
      rev: 5.9.2
      hooks:
        - id: isort
          files: '\.py'
        - id: isort
          files: 'app/.*'
        - id: isort
          files: 'tests/.*'
  -   repo: https://github.com/psf/black
      rev: 21.7b0
      hooks:
        - id: black
          language_version: python3
  -   repo: https://github.com/pycqa/pylint
      rev: v2.9.5
      hooks:
        - id: pylint
          exclude: ^migrations/
          args:
            - --errors-only
            - --rcfile=.pylintrc
            - --disable=import-error
          additional_dependencies: [pylint-venv]
  -   repo: https://github.com/pre-commit/mirrors-mypy
      rev: v0.910
      hooks:
      -   id: mypy
          exclude: ^tests/
          args: [--ignore-missing-imports]
          additional_dependencies: [pydantic]
