name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: dependencies
        run: |
          pip install poetry
          poetry install
          source `poetry env info --path`/bin/activate

      - name: isort
        run: |
          poetry run isort .

      - name: black
        run: |
          poetry run black --check .

      - name: mypy
        run: |
          poetry run mypy .

      - name: pylint
        run: |
          poetry run pylint --errors-only app

      - name: pytest
        run: |
          source `poetry env info --path`/bin/activate
          alembic upgrade head
          poetry run pytest -s -vv -x tests/ --cov=app
        env:
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          DB_HOST: 127.0.0.1
