name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  action:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres        
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v1
      
      - name: install python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          
      - name: install requirements
        run: pip3 install --no-cache-dir -r requirements.prod.txt -r requirements.dev.txt
        
      - name: run checks and tests
        run: ./docker-entrypoint.sh tests
        env:
          DB_HOST: postgres
