name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ github.token }}
      - run: pip install poetry
      - run: task install
      - run: task lint-ci

  pytest:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - uses: arduino/setup-task@v1
        with:
          repo-token: ${{ github.token }}
      - run: pip install poetry
      - run: task install
      - run: task tests
        env:
          ENVIRONMENT: dev
          PYTHONDONTWRITEBYTECODE: 1
          PYTHONUNBUFFERED: 1
          DB_HOST: 127.0.0.1
